name: lyricpad 
version: '1.0'  
summary: Powerful lyrics search app  
description: |
  Qt App for searching lyrics from web.

grade: stable  
confinement: strict
icon: snap/gui/icon.png  

architectures:
  - build-on: amd64
    run-on: amd64

apps:
  lyricpad:
    command: desktop-launch lyricpad
    environment:
       QT_STYLE_OVERRIDE: "gtk"
    plugs:
        - home
        - unity7
        - network
        - opengl
        - x11
        - desktop
        - gsettings
        - hardware-observe
        - desktop-legacy

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/usr/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/usr/share/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/usr/share/sounds
    default-provider: gtk-common-themes

parts:
  qt:
    plugin: qmake
    qt-version: qt5
    source-type: git
    source: https://github.com/keshavbhatt/lyricpad.git
    build-packages:
            - build-essential
            - qtbase5-dev
    stage:
          - -usr/share/pkgconfig
    stage-packages:
            - libqt5x11extras5
            - libdb5.3
            - libglib2.0-bin
            - python
            - python3-bs4
            - python3-requests
            - python3-lxml
    after: [desktop-qt5]
